# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lndgrpc/compiled/chainnotifier.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$lndgrpc/compiled/chainnotifier.proto\x12\x08\x63hainrpc\"S\n\x0b\x43onfRequest\x12\x0c\n\x04txid\x18\x01 \x01(\x0c\x12\x0e\n\x06script\x18\x02 \x01(\x0c\x12\x11\n\tnum_confs\x18\x03 \x01(\r\x12\x13\n\x0bheight_hint\x18\x04 \x01(\r\"Y\n\x0b\x43onfDetails\x12\x0e\n\x06raw_tx\x18\x01 \x01(\x0c\x12\x12\n\nblock_hash\x18\x02 \x01(\x0c\x12\x14\n\x0c\x62lock_height\x18\x03 \x01(\r\x12\x10\n\x08tx_index\x18\x04 \x01(\r\"\x07\n\x05Reorg\"]\n\tConfEvent\x12%\n\x04\x63onf\x18\x01 \x01(\x0b\x32\x15.chainrpc.ConfDetailsH\x00\x12 \n\x05reorg\x18\x02 \x01(\x0b\x32\x0f.chainrpc.ReorgH\x00\x42\x07\n\x05\x65vent\"\'\n\x08Outpoint\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x12\r\n\x05index\x18\x02 \x01(\r\"Y\n\x0cSpendRequest\x12$\n\x08outpoint\x18\x01 \x01(\x0b\x32\x12.chainrpc.Outpoint\x12\x0e\n\x06script\x18\x02 \x01(\x0c\x12\x13\n\x0bheight_hint\x18\x03 \x01(\r\"\xa7\x01\n\x0cSpendDetails\x12-\n\x11spending_outpoint\x18\x01 \x01(\x0b\x32\x12.chainrpc.Outpoint\x12\x17\n\x0fraw_spending_tx\x18\x02 \x01(\x0c\x12\x18\n\x10spending_tx_hash\x18\x03 \x01(\x0c\x12\x1c\n\x14spending_input_index\x18\x04 \x01(\r\x12\x17\n\x0fspending_height\x18\x05 \x01(\r\"`\n\nSpendEvent\x12\'\n\x05spend\x18\x01 \x01(\x0b\x32\x16.chainrpc.SpendDetailsH\x00\x12 \n\x05reorg\x18\x02 \x01(\x0b\x32\x0f.chainrpc.ReorgH\x00\x42\x07\n\x05\x65vent\"*\n\nBlockEpoch\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\r2\xe7\x01\n\rChainNotifier\x12I\n\x19RegisterConfirmationsNtfn\x12\x15.chainrpc.ConfRequest\x1a\x13.chainrpc.ConfEvent0\x01\x12\x43\n\x11RegisterSpendNtfn\x12\x16.chainrpc.SpendRequest\x1a\x14.chainrpc.SpendEvent0\x01\x12\x46\n\x16RegisterBlockEpochNtfn\x12\x14.chainrpc.BlockEpoch\x1a\x14.chainrpc.BlockEpoch0\x01\x42\x30Z.github.com/lightningnetwork/lnd/lnrpc/chainrpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lndgrpc.compiled.chainnotifier_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z.github.com/lightningnetwork/lnd/lnrpc/chainrpc'
  _CONFREQUEST._serialized_start=50
  _CONFREQUEST._serialized_end=133
  _CONFDETAILS._serialized_start=135
  _CONFDETAILS._serialized_end=224
  _REORG._serialized_start=226
  _REORG._serialized_end=233
  _CONFEVENT._serialized_start=235
  _CONFEVENT._serialized_end=328
  _OUTPOINT._serialized_start=330
  _OUTPOINT._serialized_end=369
  _SPENDREQUEST._serialized_start=371
  _SPENDREQUEST._serialized_end=460
  _SPENDDETAILS._serialized_start=463
  _SPENDDETAILS._serialized_end=630
  _SPENDEVENT._serialized_start=632
  _SPENDEVENT._serialized_end=728
  _BLOCKEPOCH._serialized_start=730
  _BLOCKEPOCH._serialized_end=772
  _CHAINNOTIFIER._serialized_start=775
  _CHAINNOTIFIER._serialized_end=1006
# @@protoc_insertion_point(module_scope)
