# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lndgrpc/compiled/dev.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lndgrpc.compiled import lightning_pb2 as lndgrpc_dot_compiled_dot_lightning__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lndgrpc/compiled/dev.proto',
  package='devrpc',
  syntax='proto3',
  serialized_options=b'Z,github.com/lightningnetwork/lnd/lnrpc/devrpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1alndgrpc/compiled/dev.proto\x12\x06\x64\x65vrpc\x1a lndgrpc/compiled/lightning.proto\"\x15\n\x13ImportGraphResponse2F\n\x03\x44\x65v\x12?\n\x0bImportGraph\x12\x13.lnrpc.ChannelGraph\x1a\x1b.devrpc.ImportGraphResponseB.Z,github.com/lightningnetwork/lnd/lnrpc/devrpcb\x06proto3'
  ,
  dependencies=[lndgrpc_dot_compiled_dot_lightning__pb2.DESCRIPTOR,])




_IMPORTGRAPHRESPONSE = _descriptor.Descriptor(
  name='ImportGraphResponse',
  full_name='devrpc.ImportGraphResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['ImportGraphResponse'] = _IMPORTGRAPHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImportGraphResponse = _reflection.GeneratedProtocolMessageType('ImportGraphResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTGRAPHRESPONSE,
  '__module__' : 'lndgrpc.compiled.dev_pb2'
  # @@protoc_insertion_point(class_scope:devrpc.ImportGraphResponse)
  })
_sym_db.RegisterMessage(ImportGraphResponse)


DESCRIPTOR._options = None

_DEV = _descriptor.ServiceDescriptor(
  name='Dev',
  full_name='devrpc.Dev',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=95,
  serialized_end=165,
  methods=[
  _descriptor.MethodDescriptor(
    name='ImportGraph',
    full_name='devrpc.Dev.ImportGraph',
    index=0,
    containing_service=None,
    input_type=lndgrpc_dot_compiled_dot_lightning__pb2._CHANNELGRAPH,
    output_type=_IMPORTGRAPHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEV)

DESCRIPTOR.services_by_name['Dev'] = _DEV

# @@protoc_insertion_point(module_scope)
