# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lndgrpc/compiled/peers.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lndgrpc.compiled import lightning_pb2 as lndgrpc_dot_compiled_dot_lightning__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lndgrpc/compiled/peers.proto',
  package='peersrpc',
  syntax='proto3',
  serialized_options=b'Z.github.com/lightningnetwork/lnd/lnrpc/peersrpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1clndgrpc/compiled/peers.proto\x12\x08peersrpc\x1a lndgrpc/compiled/lightning.proto\"N\n\x13UpdateAddressAction\x12&\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x16.peersrpc.UpdateAction\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"e\n\x13UpdateFeatureAction\x12&\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x16.peersrpc.UpdateAction\x12&\n\x0b\x66\x65\x61ture_bit\x18\x02 \x01(\x0e\x32\x11.lnrpc.FeatureBit\"\xad\x01\n\x1dNodeAnnouncementUpdateRequest\x12\x36\n\x0f\x66\x65\x61ture_updates\x18\x01 \x03(\x0b\x32\x1d.peersrpc.UpdateFeatureAction\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\r\n\x05\x61lias\x18\x03 \x01(\t\x12\x36\n\x0f\x61\x64\x64ress_updates\x18\x04 \x03(\x0b\x32\x1d.peersrpc.UpdateAddressAction\"8\n\x1eNodeAnnouncementUpdateResponse\x12\x16\n\x03ops\x18\x01 \x03(\x0b\x32\t.lnrpc.Op*#\n\x0cUpdateAction\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\n\n\x06REMOVE\x10\x01*i\n\nFeatureSet\x12\x0c\n\x08SET_INIT\x10\x00\x12\x15\n\x11SET_LEGACY_GLOBAL\x10\x01\x12\x10\n\x0cSET_NODE_ANN\x10\x02\x12\x0f\n\x0bSET_INVOICE\x10\x03\x12\x13\n\x0fSET_INVOICE_AMP\x10\x04\x32t\n\x05Peers\x12k\n\x16UpdateNodeAnnouncement\x12\'.peersrpc.NodeAnnouncementUpdateRequest\x1a(.peersrpc.NodeAnnouncementUpdateResponseB0Z.github.com/lightningnetwork/lnd/lnrpc/peersrpcb\x06proto3'
  ,
  dependencies=[lndgrpc_dot_compiled_dot_lightning__pb2.DESCRIPTOR,])

_UPDATEACTION = _descriptor.EnumDescriptor(
  name='UpdateAction',
  full_name='peersrpc.UpdateAction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REMOVE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=493,
  serialized_end=528,
)
_sym_db.RegisterEnumDescriptor(_UPDATEACTION)

UpdateAction = enum_type_wrapper.EnumTypeWrapper(_UPDATEACTION)
_FEATURESET = _descriptor.EnumDescriptor(
  name='FeatureSet',
  full_name='peersrpc.FeatureSet',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SET_INIT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_LEGACY_GLOBAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_NODE_ANN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_INVOICE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_INVOICE_AMP', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=530,
  serialized_end=635,
)
_sym_db.RegisterEnumDescriptor(_FEATURESET)

FeatureSet = enum_type_wrapper.EnumTypeWrapper(_FEATURESET)
ADD = 0
REMOVE = 1
SET_INIT = 0
SET_LEGACY_GLOBAL = 1
SET_NODE_ANN = 2
SET_INVOICE = 3
SET_INVOICE_AMP = 4



_UPDATEADDRESSACTION = _descriptor.Descriptor(
  name='UpdateAddressAction',
  full_name='peersrpc.UpdateAddressAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='peersrpc.UpdateAddressAction.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='peersrpc.UpdateAddressAction.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=154,
)


_UPDATEFEATUREACTION = _descriptor.Descriptor(
  name='UpdateFeatureAction',
  full_name='peersrpc.UpdateFeatureAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='peersrpc.UpdateFeatureAction.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature_bit', full_name='peersrpc.UpdateFeatureAction.feature_bit', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=257,
)


_NODEANNOUNCEMENTUPDATEREQUEST = _descriptor.Descriptor(
  name='NodeAnnouncementUpdateRequest',
  full_name='peersrpc.NodeAnnouncementUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_updates', full_name='peersrpc.NodeAnnouncementUpdateRequest.feature_updates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='peersrpc.NodeAnnouncementUpdateRequest.color', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alias', full_name='peersrpc.NodeAnnouncementUpdateRequest.alias', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address_updates', full_name='peersrpc.NodeAnnouncementUpdateRequest.address_updates', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=433,
)


_NODEANNOUNCEMENTUPDATERESPONSE = _descriptor.Descriptor(
  name='NodeAnnouncementUpdateResponse',
  full_name='peersrpc.NodeAnnouncementUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ops', full_name='peersrpc.NodeAnnouncementUpdateResponse.ops', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=491,
)

_UPDATEADDRESSACTION.fields_by_name['action'].enum_type = _UPDATEACTION
_UPDATEFEATUREACTION.fields_by_name['action'].enum_type = _UPDATEACTION
_UPDATEFEATUREACTION.fields_by_name['feature_bit'].enum_type = lndgrpc_dot_compiled_dot_lightning__pb2._FEATUREBIT
_NODEANNOUNCEMENTUPDATEREQUEST.fields_by_name['feature_updates'].message_type = _UPDATEFEATUREACTION
_NODEANNOUNCEMENTUPDATEREQUEST.fields_by_name['address_updates'].message_type = _UPDATEADDRESSACTION
_NODEANNOUNCEMENTUPDATERESPONSE.fields_by_name['ops'].message_type = lndgrpc_dot_compiled_dot_lightning__pb2._OP
DESCRIPTOR.message_types_by_name['UpdateAddressAction'] = _UPDATEADDRESSACTION
DESCRIPTOR.message_types_by_name['UpdateFeatureAction'] = _UPDATEFEATUREACTION
DESCRIPTOR.message_types_by_name['NodeAnnouncementUpdateRequest'] = _NODEANNOUNCEMENTUPDATEREQUEST
DESCRIPTOR.message_types_by_name['NodeAnnouncementUpdateResponse'] = _NODEANNOUNCEMENTUPDATERESPONSE
DESCRIPTOR.enum_types_by_name['UpdateAction'] = _UPDATEACTION
DESCRIPTOR.enum_types_by_name['FeatureSet'] = _FEATURESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateAddressAction = _reflection.GeneratedProtocolMessageType('UpdateAddressAction', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEADDRESSACTION,
  '__module__' : 'lndgrpc.compiled.peers_pb2'
  # @@protoc_insertion_point(class_scope:peersrpc.UpdateAddressAction)
  })
_sym_db.RegisterMessage(UpdateAddressAction)

UpdateFeatureAction = _reflection.GeneratedProtocolMessageType('UpdateFeatureAction', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEFEATUREACTION,
  '__module__' : 'lndgrpc.compiled.peers_pb2'
  # @@protoc_insertion_point(class_scope:peersrpc.UpdateFeatureAction)
  })
_sym_db.RegisterMessage(UpdateFeatureAction)

NodeAnnouncementUpdateRequest = _reflection.GeneratedProtocolMessageType('NodeAnnouncementUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _NODEANNOUNCEMENTUPDATEREQUEST,
  '__module__' : 'lndgrpc.compiled.peers_pb2'
  # @@protoc_insertion_point(class_scope:peersrpc.NodeAnnouncementUpdateRequest)
  })
_sym_db.RegisterMessage(NodeAnnouncementUpdateRequest)

NodeAnnouncementUpdateResponse = _reflection.GeneratedProtocolMessageType('NodeAnnouncementUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _NODEANNOUNCEMENTUPDATERESPONSE,
  '__module__' : 'lndgrpc.compiled.peers_pb2'
  # @@protoc_insertion_point(class_scope:peersrpc.NodeAnnouncementUpdateResponse)
  })
_sym_db.RegisterMessage(NodeAnnouncementUpdateResponse)


DESCRIPTOR._options = None

_PEERS = _descriptor.ServiceDescriptor(
  name='Peers',
  full_name='peersrpc.Peers',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=637,
  serialized_end=753,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateNodeAnnouncement',
    full_name='peersrpc.Peers.UpdateNodeAnnouncement',
    index=0,
    containing_service=None,
    input_type=_NODEANNOUNCEMENTUPDATEREQUEST,
    output_type=_NODEANNOUNCEMENTUPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PEERS)

DESCRIPTOR.services_by_name['Peers'] = _PEERS

# @@protoc_insertion_point(module_scope)
