# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lndgrpc/compiled/stateservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#lndgrpc/compiled/stateservice.proto\x12\x05lnrpc\"\x17\n\x15SubscribeStateRequest\";\n\x16SubscribeStateResponse\x12!\n\x05state\x18\x01 \x01(\x0e\x32\x12.lnrpc.WalletState\"\x11\n\x0fGetStateRequest\"5\n\x10GetStateResponse\x12!\n\x05state\x18\x01 \x01(\x0e\x32\x12.lnrpc.WalletState*s\n\x0bWalletState\x12\x10\n\x0cNON_EXISTING\x10\x00\x12\n\n\x06LOCKED\x10\x01\x12\x0c\n\x08UNLOCKED\x10\x02\x12\x0e\n\nRPC_ACTIVE\x10\x03\x12\x11\n\rSERVER_ACTIVE\x10\x04\x12\x15\n\x10WAITING_TO_START\x10\xff\x01\x32\x95\x01\n\x05State\x12O\n\x0eSubscribeState\x12\x1c.lnrpc.SubscribeStateRequest\x1a\x1d.lnrpc.SubscribeStateResponse0\x01\x12;\n\x08GetState\x12\x16.lnrpc.GetStateRequest\x1a\x17.lnrpc.GetStateResponseB\'Z%github.com/lightningnetwork/lnd/lnrpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lndgrpc.compiled.stateservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z%github.com/lightningnetwork/lnd/lnrpc'
  _WALLETSTATE._serialized_start=206
  _WALLETSTATE._serialized_end=321
  _SUBSCRIBESTATEREQUEST._serialized_start=46
  _SUBSCRIBESTATEREQUEST._serialized_end=69
  _SUBSCRIBESTATERESPONSE._serialized_start=71
  _SUBSCRIBESTATERESPONSE._serialized_end=130
  _GETSTATEREQUEST._serialized_start=132
  _GETSTATEREQUEST._serialized_end=149
  _GETSTATERESPONSE._serialized_start=151
  _GETSTATERESPONSE._serialized_end=204
  _STATE._serialized_start=324
  _STATE._serialized_end=473
# @@protoc_insertion_point(module_scope)
