# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lndgrpc/compiled/verrpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlndgrpc/compiled/verrpc.proto\x12\x06verrpc\"\x10\n\x0eVersionRequest\"\xb9\x01\n\x07Version\x12\x0e\n\x06\x63ommit\x18\x01 \x01(\t\x12\x13\n\x0b\x63ommit_hash\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x11\n\tapp_major\x18\x04 \x01(\r\x12\x11\n\tapp_minor\x18\x05 \x01(\r\x12\x11\n\tapp_patch\x18\x06 \x01(\r\x12\x17\n\x0f\x61pp_pre_release\x18\x07 \x01(\t\x12\x12\n\nbuild_tags\x18\x08 \x03(\t\x12\x12\n\ngo_version\x18\t \x01(\t2B\n\tVersioner\x12\x35\n\nGetVersion\x12\x16.verrpc.VersionRequest\x1a\x0f.verrpc.VersionB.Z,github.com/lightningnetwork/lnd/lnrpc/verrpcb\x06proto3')



_VERSIONREQUEST = DESCRIPTOR.message_types_by_name['VersionRequest']
_VERSION = DESCRIPTOR.message_types_by_name['Version']
VersionRequest = _reflection.GeneratedProtocolMessageType('VersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONREQUEST,
  '__module__' : 'lndgrpc.compiled.verrpc_pb2'
  # @@protoc_insertion_point(class_scope:verrpc.VersionRequest)
  })
_sym_db.RegisterMessage(VersionRequest)

Version = _reflection.GeneratedProtocolMessageType('Version', (_message.Message,), {
  'DESCRIPTOR' : _VERSION,
  '__module__' : 'lndgrpc.compiled.verrpc_pb2'
  # @@protoc_insertion_point(class_scope:verrpc.Version)
  })
_sym_db.RegisterMessage(Version)

_VERSIONER = DESCRIPTOR.services_by_name['Versioner']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/lightningnetwork/lnd/lnrpc/verrpc'
  _VERSIONREQUEST._serialized_start=41
  _VERSIONREQUEST._serialized_end=57
  _VERSION._serialized_start=60
  _VERSION._serialized_end=245
  _VERSIONER._serialized_start=247
  _VERSIONER._serialized_end=313
# @@protoc_insertion_point(module_scope)
