# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lndgrpc/compiled/watchtower.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!lndgrpc/compiled/watchtower.proto\x12\rwatchtowerrpc\"\x10\n\x0eGetInfoRequest\"B\n\x0fGetInfoResponse\x12\x0e\n\x06pubkey\x18\x01 \x01(\x0c\x12\x11\n\tlisteners\x18\x02 \x03(\t\x12\x0c\n\x04uris\x18\x03 \x03(\t2V\n\nWatchtower\x12H\n\x07GetInfo\x12\x1d.watchtowerrpc.GetInfoRequest\x1a\x1e.watchtowerrpc.GetInfoResponseB5Z3github.com/lightningnetwork/lnd/lnrpc/watchtowerrpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lndgrpc.compiled.watchtower_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3github.com/lightningnetwork/lnd/lnrpc/watchtowerrpc'
  _GETINFOREQUEST._serialized_start=52
  _GETINFOREQUEST._serialized_end=68
  _GETINFORESPONSE._serialized_start=70
  _GETINFORESPONSE._serialized_end=136
  _WATCHTOWER._serialized_start=138
  _WATCHTOWER._serialized_end=224
# @@protoc_insertion_point(module_scope)
